image: tdio/janus:1.0.2

cache:
  paths:
    - node_modules/

variables:
  NODE_ENV: 'production'
  DEVTOOL: 'source-map'
  CI_NEXT_VERSION: 1.4.3

before_script:
  - git-ci setup-devpot --preset v1.0.1
  - yarn --production=false

after_script:
  - git-ci cleanup-build-cache

stages:
 - build
 - release

deployment:
  tags:
    - sandbox
  script:
    - yarn lint
    - yarn build
    - yarn test
    - git release-npm -r patch -t dev -f
  stage: build
  only:
    - branches
    - triggers
  except:
    - master

release:
  tags:
    - sandbox
  script:
    - yarn build
    - git release-npm -r patch -t next -f
  stage: release
  only:
    - tags
