image: tdio/janus:1.0.1

cache:
  paths:
    - node_modules/

variables:
  NODE_ENV: 'production'
  DEVTOOL: 'source-map'
  CI_NEXT_VERSION: 1.4.3

before_script:
  - git-ci setup-devpot --preset v1.0.1
  - yarn --production=false

after_script:
  - git-ci cleanup-build-cache

stages:
 - build
 - prerelease
 - release

deployment:
  tags:
    - sandbox
  script:
    - yarn lint
    - yarn build
    - yarn test
  stage: build
  only:
    - devel
    - triggers

prerelease:
  tags:
    - sandbox
  script:
    - yarn lint
    - yarn build
    - yarn test
    - git release-npm -t insiders --next-version ${CI_NEXT_VERSION} -f
  stage: prerelease
  only:
    - master
    - triggers

release:
  tags:
    - sandbox
  script:
    - yarn build
    - git release-npm -t next -f
  stage: release
  only:
    - tags
