cache:
  paths:
    - node_modules/

variables:
  NODE_ENV: 'production'
  DEVTOOL: 'source-map'
  CI_NEXT_VERSION: 1.4.2

before_script:
  - npm config get registry
  - yarn --production=false

stages:
 - build
 - release

deployment:
  tags:
    - development
  script:
    - yarn lint
    - yarn build
    - yarn test
    - git release-npm -t insiders --next-version ${CI_NEXT_VERSION} -f
  stage: build
  only:
    - branches
    - triggers

release:
  tags:
    - development
  script:
    - yarn build
    - git release-npm -t next -f
  stage: release
  only:
    - tags
